### ISSUE TITLE
CouchDB already configured (fresh install) 

### ISSUE THREAD

**Issue by jackalblood** [compactd/compactd#38]
Hi there

I've tried to install Compact-d and I managed to get npm and couchdb installed just fine however when I run compactd - configure I'm told couchdb is already configured

This is unlikely as I used apt-get install couchdb to install it just for compactd I haven't touched it i went immediately to compactd after the installation of couchdb finshed I've also tried apt-get remove couchdb -purge and reinstalled with no luck it still says already configured 

Here are my steps exactly 

```
apt-get install couchdb

compactd -configure


  This wizard will guide you through the configuration of compactd
  This should only take one or two minutes...

  ✔ FFprobe and FFmpeg found in /usr/local/bin/ffmpeg
  ✔ You secret is secure (entropy: 1227)
  ✔ Folder /home/user/.compactd/ is writable
  ✘ CouchDB is already configured
```
I'm very lost at what to do next I'm very interested in trying compactd and I'm sure it's something simple I'm missing but at the moment I'm totally stumped 

Thank you

**Comment by vinz243** [comment]
Thanks for the issue, can you do:

````
curl http://localhost:5984/_session
```

**Comment by jackalblood** [comment]
$ curl http://localhost:5984/
{"couchdb":"Welcome","uuid":"46b2a4f30c611acec3cbc317be49849f","version":"1.6.0","vendor":{"name":"Ubuntu","version":"15.10"}}


 curl http://localhost:5984/_session
{"ok":true,"userCtx":{"name":null,"roles":["_admin"]},"info":{"authentication_db":"_users","authentication_handlers":["oauth","cookie","default"],"authenticated":"default"}}

here yo go mate hope it helps

**Comment by vinz243** [comment]
>` "version":"1.6.0"`

that must be the issue, compactd support bversion 2+.

Try using
```
sudo apt-get remove couchdb couchdb-bin couchdb-common -f
sudo apt-get install python-software-properties
sudo apt-add-repository ppa:couchdb/stable
sudo apt-get update
sudo apt-get install couchdb couchdb-bin couchdb-common -f
```

**Comment by jackalblood** [comment]
[joemannix8@Reaper]:(6.7Gb)~$ compactd --configure

  Thanks for downloading compactd 1.2.1 !

  This wizard will guide you through the configuration of compactd
  This should only take one or two minutes...

  ✔ FFprobe and FFmpeg found in /usr/local/bin/ffmpeg
  ✔ You secret is secure (entropy: 1227)
  ✔ Folder /home/joemannix8/.compactd/ is writable
  ✘ CouchDB is already configured

   Couldn't finish configuration

**Comment by jackalblood** [comment]
I GOT IT!

Heres what i did 

echo "deb https://apache.bintray.com/couchdb-deb xenial main" \
    | sudo tee -a /etc/apt/sources.list

curl -L https://couchdb.apache.org/repo/bintray-pubkey.asc \
    | sudo apt-key add -

sudo apt-get update && sudo apt-get install couchdb

simple fix really if i had checked my version number i could of fixed it without asking for help i'm very sorry however hopefully this can help you in the future

**Comment by vinz243** [comment]
It's OK, glad your issue has been solved :)
