### ISSUE TITLE
When I scan my library, new albums / artists aren't displayed directly

### ISSUE THREAD

**Issue by almet** [compactd/compactd#59]
I actually need to reload the app, which interrupt the sound. Would it be possible to update directly?

**Comment by vinz243** [comment]
It is technically possible and relatively easy to implement. Some changes should update the UI automatically, like when editing your library content (e.g. replacing an artwork) it should immediately update UI. However it cannot work if the socket proxy isn't working (the one on port 9001)

**Comment by almet** [comment]
It actually works when the socket proxy is on.
